server:
  port: 8080

eureka:
  intance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EmpresaInnova
          uri: lb://EmpresaInnova
          predicates:
            - Path=/empresa/**
        - id: MyGranProyecto
          uri: lb://MyGranProyecto
          predicates:
            - Path=/producto/**
